name: Submit to Covalent Cloud

on:
#   schedule: # un comment to run every 30 minutes
    # - cron: "*/30 * * * *" 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Run script
        run: python .github/workflows/script.py
        env:
          CC_API_KEY: ${{ secrets.CC_API_KEY }}

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions